### ISSUE TITLE
Build fails with lots of "cc1plus: all warnings being treated as error"

### ISSUE THREAD

**Issue by umeshmohan** [spajak/cef-pdf#1]
Same error with both ninja and unix makefiles.
Trying to compile on Ubuntu 16.04.01
Build outputs attached
[build.ninja.log.txt](https://github.com/spajak/cef-pdf/files/840329/build.ninja.log.txt)
[build.Makefiles.log.txt](https://github.com/spajak/cef-pdf/files/840330/build.Makefiles.log.txt)

**Comment by ammaroff** [comment]
Same for VS2015 and VS2017 
cmake with VS template generator Success and VS build failed
cmake with Ninja template generator Success and Ninja build failed

**Comment by spajak** [comment]
Which CEF version? Current master works on CEF 3.2883.1539.gd7f087e
Also, it looks like you are compiling with -Werror flag. -Wno-error should be used instead

**Comment by umeshmohan** [comment]
Same errors in multiple CEF versions. Changing Werror to Wno-error changes the warnings reported but build still fails. I was able to compile it using the approach suggested by CEF. My forked repo here: https://github.com/umeshmohan/cef-pdf
With the changes I have made, there are no warnings during compilation and so no need to change Werror to Wno-error.
