### ISSUE TITLE
Linux release.

### ISSUE THREAD

**Issue by beckyconning** [spajak/cef-pdf#13]
Can I help with this? What would be involved?

**Comment by spajak** [comment]
Actually I have Linux release, but it is very heavy; 100 MB or so. I'm thinking of releasing only cef-pdf executable and some kind of an instruction or script to download and install CEF binaries alongside.
What do You think?

**Comment by beckyconning** [comment]
I'm not sure that `cef-pdf` is useful without the `CEF` binaries so to me it seems like a stronger idea to release the entire linux executable.

**Comment by beckyconning** [comment]
99% of users will need to download the binaries during installation anyway.

**Comment by ghost** [comment]
I wrote a debian based Dockerfile that automates compiling cef-pdf with the CEF binaries. Let me know if it would help in this context and I can open a PR.

**Comment by spajak** [comment]
Linux release already included. Closing
