### ISSUE TITLE
[feature request] customize PDF metadata

### ISSUE THREAD

**Issue by ghost** [spajak/cef-pdf#15]
As a user, I would like the ability to customize the PDF metadata. (Creator and Producer specifically) Right now it lists the cef user agent and underlying skia/PDF library as the content creator.

**Comment by anko** [comment]
Have you considered using a separate tool? [Exiftool](https://en.wikipedia.org/wiki/ExifTool) worked for me.

**Comment by ghost** [comment]
ah, I have not @anko. Thanks that could solve what I am looking for.

**Comment by spajak** [comment]
I think external tool would be the best choice here. Closing
