### ISSUE TITLE
errors for invalid cli flag calls or more forgiving syntax

### ISSUE THREAD

**Issue by ghost** [spajak/cef-pdf#2]
Thanks for building this tool. It looks much more promising and reliable than other html to pdf binaries/libraries I have worked with.
I have been using it successfully so far but accidentally typed:
```
 $ src/Release/cef-pdf.app/Contents/MacOS/cef-pdf --file ./test.html ./test.pdf
```
Instead of erroring, the binary unexpectedly overwrite test.html. It would be nice if the cli threw an error that I mistyped the `--file` switch, or was a tad more flexible.

**Comment by spajak** [comment]
Thanks for pointing this out. Already fixed in devel branch

**Comment by ghost** [comment]
ah, thanks @spajak ! will close this then
