### ISSUE TITLE
[feature request] configuring runtime verbosity for debugging?

### ISSUE THREAD

**Issue by ghost** [spajak/cef-pdf#3]
is it possible to increase the runtime verbosity when the PDF generation occurs? I think this would be helpful for troubleshooting complex pages being generated. If it is relatively simple, I can help contribute documentation for it.

**Comment by spajak** [comment]
This is not a problem. What specific messages would like to see?

**Comment by ghost** [comment]
great to hear. Starting out out I think a single verbose level of debugging would be helpful noting what steps in converting the HTML to the PDF have occurred. As a user I've primarily want to see the operations are completing successfully and perhaps additional diagnostic info for when assets or other things within the PDF generation aren't occurring. I'm not sure if cef exposes anything here. If they do, i'd probably be fine with whatever they print out.
