### ISSUE TITLE
[feature request] accept file from standard input

### ISSUE THREAD

**Issue by ghost** [spajak/cef-pdf#7]
I am running cef-pdf from within a Linux container and would like executions to pipe file input into the container. This would enable a common pattern of running containers and destroying them afterwards so I could run omething like:
```sh
$ cat some-file.html | docker run --rm -it --env DISPLAY=172.17.0.2:99 \
	 my-cef-image cef-pdf \
	--backgrounds
```

I see this as an alternative to `--file` and `--server` options. That way I can run cef-pdf without having to save the input to disk or retrieve it from a URL.

**Comment by spajak** [comment]
That feature is partialy implemented but not activated. I'm not sure how to tell the program to output to stdout instead of a file and read from stdin. Simply omitting `--file/--url` and/or `--output`? Or use some special arguments like `-`?

**Comment by ghost** [comment]
Ah, neat! I have used [wkhtmltopdf](http://wkhtmltopdf.org/) which uses the `-` flags to indicate piping. I could also see a `--stream` or `--stdio` flag. Personally I like the command line switches because I think they document themselves when appropriately named. Next week I will look up some example projects and can post other switch names here.

**Comment by spajak** [comment]
Feature implemented in acc42e2b64f891187bfe6654f16c7cf819235138
 - `--stdin` flag - for reading from stdin.
 - no output file - for writing to stdout.

I would be very glad if you could test it.

**Comment by ghost** [comment]
wow, thanks again for working with me on these and turning them around so quickly @spajak ! I will be testing this today and will let you know.

**Comment by ghost** [comment]
Tested and verified that this is working as expected and I can pipe in and out of a container executing the command. Thank you for adding this.
