### ISSUE TITLE
http server broken in last release.

### ISSUE THREAD

**Issue by beckyconning** [spajak/cef-pdf#9]
`curl -X POST http://localhost:9288/timeout.pdf --header "Content-Location: http://www.google.com" > output.pdf`

works on 0.3.1 but hangs forever on 0.3.2 and master

**Comment by beckyconning** [comment]
It might be worth adding some curl / diff based tests to prevent such regressions in the future?

**Comment by spajak** [comment]
Preparing fix for this. That would be a good idea to add some tests

**Comment by spajak** [comment]
Fixed in `devel` branch. Please test it if you can

**Comment by beckyconning** [comment]
Will do first thing tomorrow. Thanks so much!

**Comment by beckyconning** [comment]
Yup works for me! Happy to close when its been released : ).

**Comment by beckyconning** [comment]
When is the fix for this going to be merged into master / released?

**Comment by spajak** [comment]
I think tomorrow or Sunday

**Comment by spajak** [comment]
Closing
